name: Auto Comment
on:
  pull_request:
    # types:
    #   - opened
    paths:
      - "**/computer_science/**"

jobs:
  auto-comment:
    name: Remind about duplicated lessons
    runs-on: ubuntu-latest
    steps:
      - name: Get changed CS files
        uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: |
            **/computer_science/**
          separator: ","

      - name: Check for unduplicated changes
        id: change-duplication
        env:
          CHANGED_CS_FILES: ${{ steps.changed-files.outputs.all_modified_files_count }}
        run: |
          echo "all_duplicated=$($CHANGED_CS_FILES % 2 == 0)" >> $GITHUB_OUTPUT

      - name: Comment if unduplicated changes
        if: steps.change-duplication.outputs.all_duplicated == 'false'
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="This PR includes a change to a computer science lesson, and these have separate files for each pathway's version. "
          DUPE=${{ steps.change-duplication.outputs.all_duplicated }}

          curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/TheOdinProject/curriculum/issues/${PR_NUMBER}/comments" \
            -d '{"body":"This PR includes a change to a computer science lesson and these have separate files for each pathway"}'
